# Remote Salary Benchmark
#### Are remote workers in India being underpaid when compared to their US and European Counterparts?
**Data sources:** level.fyi, World Bank PPP, DOL H-1B Enclosures  
**Tools Used:** numpy, pandas, matplotlib, seaborn  
**Author: Kunal Verma**

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
print("All the libraries have been loaded.")

All the libraries have been loaded.

In [13]:
import os
os.getcwd()

'/Users/kunalverma/Desktop/remote_salary_benchmark/notebooks'

In [16]:
df_h1b = pd.read_excel('../data/raw_data/LCA_Dislclosure_Data_FY2026_Q2.xlsx')
print(df_h1b.shape)
print(df_h1b.columns.tolist())

(210387, 98)
['CASE_NUMBER', 'CASE_STATUS', 'RECEIVED_DATE', 'DECISION_DATE', 'ORIGINAL_CERT_DATE', 'VISA_CLASS', 'JOB_TITLE', 'SOC_CODE', 'SOC_TITLE', 'FULL_TIME_POSITION', 'BEGIN_DATE', 'END_DATE', 'TOTAL_WORKER_POSITIONS', 'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT', 'CHANGE_PREVIOUS_EMPLOYMENT', 'NEW_CONCURRENT_EMPLOYMENT', 'CHANGE_EMPLOYER', 'AMENDED_PETITION', 'EMPLOYER_NAME', 'TRADE_NAME_DBA', 'EMPLOYER_ADDRESS1', 'EMPLOYER_ADDRESS2', 'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_COUNTRY', 'EMPLOYER_PROVINCE', 'EMPLOYER_PHONE', 'EMPLOYER_PHONE_EXT', 'EMPLOYER_FEIN', 'NAICS_CODE', 'EMPLOYER_POC_LAST_NAME', 'EMPLOYER_POC_FIRST_NAME', 'EMPLOYER_POC_MIDDLE_NAME', 'EMPLOYER_POC_JOB_TITLE', 'EMPLOYER_POC_ADDRESS1', 'EMPLOYER_POC_ADDRESS2', 'EMPLOYER_POC_CITY', 'EMPLOYER_POC_STATE', 'EMPLOYER_POC_POSTAL_CODE', 'EMPLOYER_POC_COUNTRY', 'EMPLOYER_POC_PROVINCE', 'EMPLOYER_POC_PHONE', 'EMPLOYER_POC_PHONE_EXT', 'EMPLOYER_POC_EMAIL', 'AGENT_REPRESENTING_EMPLOYER', 'AGENT_ATTORNEY_LAST_NAME', 'AGENT_ATTORNEY_FIRST_NAME', 'AGENT_ATTORNEY_MIDDLE_NAME', 'AGENT_ATTORNEY_ADDRESS1', 'AGENT_ATTORNEY_ADDRESS2', 'AGENT_ATTORNEY_CITY', 'AGENT_ATTORNEY_STATE', 'AGENT_ATTORNEY_POSTAL_CODE', 'AGENT_ATTORNEY_COUNTRY', 'AGENT_ATTORNEY_PROVINCE', 'AGENT_ATTORNEY_PHONE', 'AGENT_ATTORNEY_PHONE_EXT', 'AGENT_ATTORNEY_EMAIL_ADDRESS', 'LAWFIRM_NAME_BUSINESS_NAME', 'LAWFIRM_BUSINESS_FEIN', 'STATE_OF_HIGHEST_COURT', 'NAME_OF_HIGHEST_STATE_COURT', 'WORKSITE_WORKERS', 'SECONDARY_ENTITY', 'SECONDARY_ENTITY_BUSINESS_NAME', 'WORKSITE_ADDRESS1', 'WORKSITE_ADDRESS2', 'WORKSITE_CITY', 'WORKSITE_COUNTY', 'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY', 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY', 'PW_TRACKING_NUMBER', 'PW_WAGE_LEVEL', 'PW_OES_YEAR', 'PW_OTHER_SOURCE', 'PW_OTHER_YEAR', 'PW_SURVEY_PUBLISHER', 'PW_SURVEY_NAME', 'TOTAL_WORKSITE_LOCATIONS', 'AGREE_TO_LC_STATEMENT', 'H_1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'SUPPORT_H1B', 'STATUTORY_BASIS', 'APPENDIX_A_ATTACHED', 'PUBLIC_DISCLOSURE', 'PREPARER_LAST_NAME', 'PREPARER_FIRST_NAME', 'PREPARER_MIDDLE_INITIAL', 'PREPARER_BUSINESS_NAME', 'PREPARER_EMAIL']

In [18]:
cols_needed = ['CASE_STATUS', 
               'JOB_TITLE',
               'EMPLOYER_NAME',
               'EMPLOYER_CITY',
               'EMPLOYER_STATE',
               'EMPLOYER_COUNTRY',
               'WAGE_RATE_OF_PAY_FROM',
               'WAGE_UNIT_OF_PAY'
              ]
df_h1b = df_h1b[cols_needed]
print(df_h1b.shape)
df_h1b.head(10)

(210387, 8)

,CASE_STATUS,JOB_TITLE,EMPLOYER_NAME,EMPLOYER_CITY,EMPLOYER_STATE,EMPLOYER_COUNTRY,WAGE_RATE_OF_PAY_FROM,WAGE_UNIT_OF_PAY
0,Certified - Withdrawn,Specialist - Software Engineering,LTIMindtree Limited,Edison,NJ,UNITED STATES OF AMERICA,139000.00,Year
1,Certified - Withdrawn,Director of Business Development,"Structural Group, Inc.",Columbia,MD,UNITED STATES OF AMERICA,215000.00,Year
2,Certified - Withdrawn,Senior Software Developer,"Leidos, Inc.",Reston,VA,UNITED STATES OF AMERICA,163000.00,Year
3,Certified - Withdrawn,Chief Operating Officer,"George S. Hall, Inc.",Parsippany,NJ,UNITED STATES OF AMERICA,334750.00,Year
4,Certified - Withdrawn,Software Developer,RELIABLE SOFTWARE RESOURCES,NORTHVILLE,MI,UNITED STATES OF AMERICA,99600.00,Year
5,Certified - Withdrawn,Job Captain,MBH Architects Inc.,Alameda,CA,UNITED STATES OF AMERICA,94000.00,Year
6,Certified - Withdrawn,PLM Engineer,LILLI TECHNOLOGY LLC,PLANO,TX,UNITED STATES OF AMERICA,45.02,Hour
7,Certified - Withdrawn,Expert Solution Architect,Acxiom LLC,Conway,AR,UNITED STATES OF AMERICA,195000.00,Year
8,Certified - Withdrawn,Job Captain,MBH Architects Inc.,Alameda,CA,UNITED STATES OF AMERICA,93995.20,Year
9,Certified - Withdrawn,Data Analyst D,TRUSTEES OF THE UNIVERSITY OF PENNSYLVANIA,PHILADELPHIA,PA,UNITED STATES OF AMERICA,92258.36,Year

In [33]:
df_ppp = pd.read_csv('../data/raw_data/API_PA.NUS.PPP_DS2_en_csv_v2_281504.csv',skiprows = 4)
print(df_ppp.shape)
df_ppp.head()

(266, 71)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"PPP conversion factor, GDP (LCU per internatio...",PA.NUS.PPP,NaN,NaN,NaN,NaN,NaN,NaN,...,1.356637,1.370606,1.423212,1.411909,1.363954,1.327790,1.372785,1.395922,NaN,NaN
1,Africa Eastern and Southern,AFE,"PPP conversion factor, GDP (LCU per internatio...",PA.NUS.PPP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,"PPP conversion factor, GDP (LCU per internatio...",PA.NUS.PPP,NaN,NaN,NaN,NaN,NaN,NaN,...,15.420207,14.856235,15.026434,15.335243,14.587942,14.897971,14.800941,NaN,NaN,NaN
3,Africa Western and Central,AFW,"PPP conversion factor, GDP (LCU per internatio...",PA.NUS.PPP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,"PPP conversion factor, GDP (LCU per internatio...",PA.NUS.PPP,NaN,NaN,NaN,NaN,NaN,NaN,...,95.837242,111.441811,124.439606,146.909134,174.090515,191.953512,218.506583,265.840925,NaN,NaN

In [34]:
df_ppp = df_ppp[['Country Name', 'Country Code', '2024']]
df_ppp.columns = ['country', 'country_code', 'ppp_2024']
print(df_ppp.shape)
df_ppp.head(10)

(266, 3)

                       country country_code    ppp_2024
0                        Aruba          ABW    1.395922
1  Africa Eastern and Southern          AFE         NaN
2                  Afghanistan          AFG         NaN
3   Africa Western and Central          AFW         NaN
4                       Angola          AGO  265.840925
5                      Albania          ALB   39.667384
6                      Andorra          AND    0.607839
7                   Arab World          ARB         NaN
8         United Arab Emirates          ARE    2.330334
9                    Argentina          ARG  419.901040

In [36]:
df_levels = pd.read_csv('../data/raw_data/salaries.csv')
print(df_levels.shape)
print(df_levels.columns.tolist())
df_levels.head(10)

(16494, 11)
['work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2024,MI,FT,Data Scientist,120000,USD,120000,AU,0,AU,S
1,2024,MI,FT,Data Scientist,70000,USD,70000,AU,0,AU,S
2,2024,MI,CT,Data Scientist,130000,USD,130000,US,0,US,M
3,2024,MI,CT,Data Scientist,110000,USD,110000,US,0,US,M
4,2024,MI,FT,Data Science Manager,240000,USD,240000,US,0,US,M
5,2024,MI,FT,Data Science Manager,180000,USD,180000,US,0,US,M
6,2024,SE,FT,Business Intelligence Engineer,202800,USD,202800,US,0,US,M
7,2024,SE,FT,Business Intelligence Engineer,115000,USD,115000,US,0,US,M
8,2024,SE,FT,Data Architect,80000,GBP,100000,GB,0,GB,M
9,2024,SE,FT,Data Architect,45000,GBP,56250,GB,0,GB,M

In [37]:
cols_needed = ['job_title',
               'experience_level',
               'salary_in_usd',
               'employee_residence',
               'employment_type']
df_levels = df_levels[cols_needed]
print(df_levels.shape)
df_levels.head(10)

(16494, 5)

,job_title,experience_level,salary_in_usd,employee_residence,employment_type
0,Data Scientist,MI,120000,AU,FT
1,Data Scientist,MI,70000,AU,FT
2,Data Scientist,MI,130000,US,CT
3,Data Scientist,MI,110000,US,CT
4,Data Science Manager,MI,240000,US,FT
5,Data Science Manager,MI,180000,US,FT
6,Business Intelligence Engineer,SE,202800,US,FT
7,Business Intelligence Engineer,SE,115000,US,FT
8,Data Architect,SE,100000,GB,FT
9,Data Architect,SE,56250,GB,FT

In [38]:
df_h1b.to_csv('../data/raw_data/h1b_raw.csv', index=False)
df_ppp.to_csv('../data/raw_data/ppp_raw.csv', index=False)
df_levels.to_csv('../data/raw_data/levels_raw.csv', index=False)

print("all 3 datasets saved")

all 3 datasets saved